### ISSUE TITLE
Improve the website performance and security with no cost

### ISSUE THREAD

**Issue by MinorMole** [Coceki/new-pekobutton#2]
You should consider making a static website by using [Jekyll](https://jekyllrb.com/) to generate a static website and host it on [GitHub Pages](https://pages.github.com/) that link to your domain (https://peko.top) that using [Cloudflare](https://www.cloudflare.com/) DNS which also free.

The reason is:
- GitHub Pages and Cloudflare is **FREE**
- No downtime and no dedicated server needed because GitHub's server is really strong and even if it out of service your website can be accessible via Cloudflare cache as a backhaul which also have the most reliable server to offer on the market.
- DDOS-proof and spam-proof
- The fastest speed that any free service can offer even beat most of the paid service.

The example website that I made hosting by using a combination of Jekyll + Cloudflare's DNS + GitHub Pages: https://konayuki.moe

**Comment by Coceki** [comment]
Sites using Cloudflare's free plan is nearly unaccessable for users in China. I'll find a better plan after my final exam.😅

**Comment by Coceki** [comment]
Now the site is on Netlify when accessed from a non Chinese IP. Works well since now
