### ISSUE TITLE
Automatic Translation Selection

### ISSUE THREAD

**Issue by HayatoTenryuu** [Coceki/new-pekobutton#3]
The website defaults to Chinese text, and you have to select between English, Japanese, and Chinese in the top right hand corner. I think it is a good idea to let the user select the language, but Pekora looked at the site, it was in Chinese and she didn't see that she could use her own language.

So I think for IP addresses in Japan, China, and America/Europe, the site should automatically decide which language is best for them, if that's possible. It would just give people an easier time with it.

I can help with any translations if needed!

**Comment by Coceki** [comment]
Now language would change to your browser's language if you visit it first time😃.
