### ISSUE TITLE
voices encoded in WAV don't play on Waterfox

### ISSUE THREAD

**Issue by Craftplacer** [Coceki/new-pekobutton#4]
Please encode them all (or make them available separately) as MP3

Errors:
![2020-06-29 01:44:05 AM](https://user-images.githubusercontent.com/22963120/85961368-44ea3500-b9aa-11ea-8731-f3436f414576.png)

**Comment by Coceki** [comment]
Now every .wav was encoded to .mp3 with the same value😀
